######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 26 19:39:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ipacl.h
FORMS += ipacl.ui
SOURCES += ipacl.cpp main.cpp
