######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 29 11:15:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ipacl.h
FORMS += ipacl.ui
SOURCES += ipacl.cpp main.cpp
