######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 28 22:48:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ipacl.h
FORMS += ipacl.ui
SOURCES += ipacl.cpp main.cpp
